const DummyTransactionsArray=[
    {
        title:"Christopher Duke",
        amount:"630",
        expense:false,
        category:"Dividend",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Jodie Franco",
        amount:"1000",
        expense:false,
        category:"Lend",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Hilario Scott",
        amount:"2500",
        expense:false,
        category:"Salary",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Alejandro Ramos",
        amount:"270",
        expense:true,
        category:"Loan",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Reyes Pittman",
        amount:"700",
        expense:true,
        category:"Savings",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Ronald Hickman",
        amount:"420",
        expense:false,
        category:"Pension",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Araceli Lin",
        amount:"500",
        expense:true,
        category:"House Rent",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Nicholas Aguirre",
        amount:"15000",
        expense:false,
        category:"Salary",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Marquita Curtis",
        amount:"1000",
        expense:true,
        category:"Groceries",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Orlando Lewis",
        amount:"100",
        expense:true,
        category:"Others",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Tyrell Barnes",
        amount:"1200",
        expense:true,
        category:"Entertainment",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Kennith Carr",
        amount:"2000",
        expense:false,
        category:"Dividend",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Dino Flores",
        amount:"220",
        expense:true,
        category:"Maintenance",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Imelda Sullivan",
        amount:"2100",
        expense:true,
        category:"Education",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Susanne Garza",
        amount:"3000",
        expense:true,
        category:"Education",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Brenton Lucas",
        amount:"500",
        expense:true,
        category:"Transportation",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Gordon Lowe",
        amount:"900",
        expense:false,
        category:"Interest",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Aurora Castaneda",
        amount:"5000",
        expense:true,
        category:"House Rent",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Neville Leonard",
        amount:"3500",
        expense:false,
        category:"Profit",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Kristopher Lynch",
        amount:"390",
        expense:true,
        category:"Others",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Young Salazar",
        amount:"100",
        expense:true,
        category:"Entertainment",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Toni Gutierrez",
        amount:"500",
        expense:false,
        category:"Dividend",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Mike Haas",
        amount:"1300",
        expense:true,
        category:"Maintenance",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Myron Carrillo",
        amount:"250",
        expense:true,
        category:"Education",
        date:"25/11/2023 1:22 PM",
    },
    {
        title:"Constance Bean",
        amount:"5000",
        expense:true,
        category:"Education",
        date:"25/11/2023 1:22 PM",
    },
]

export default DummyTransactionsArray